package big.strong.disheng.user.dao;

import big.strong.disheng.user.model.IdaDataset;

public interface IdaDatasetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ida_dataset
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    int deleteByPrimaryKey(String dataset_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ida_dataset
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    int insert(IdaDataset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ida_dataset
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    int insertSelective(IdaDataset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ida_dataset
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    IdaDataset selectByPrimaryKey(String dataset_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ida_dataset
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    int updateByPrimaryKeySelective(IdaDataset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ida_dataset
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    int updateByPrimaryKey(IdaDataset record);
}