package big.strong.disheng.user.dao;

import big.strong.disheng.user.model.IdaTaskItemHist;

public interface IdaTaskItemHistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ida_task_item_hist
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    int deleteByPrimaryKey(String hist_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ida_task_item_hist
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    int insert(IdaTaskItemHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ida_task_item_hist
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    int insertSelective(IdaTaskItemHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ida_task_item_hist
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    IdaTaskItemHist selectByPrimaryKey(String hist_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ida_task_item_hist
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    int updateByPrimaryKeySelective(IdaTaskItemHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ida_task_item_hist
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    int updateByPrimaryKey(IdaTaskItemHist record);
}