package big.strong.disheng.user.model;

public class IdaDatatype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_datatype.datatype_code
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String datatype_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_datatype.datatype_name
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String datatype_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_datatype.discription
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String discription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_datatype.creator
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_datatype.created_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String created_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_datatype.updated_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String updated_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_datatype.datatype_code
     *
     * @return the value of ida_datatype.datatype_code
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getDatatype_code() {
        return datatype_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_datatype.datatype_code
     *
     * @param datatype_code the value for ida_datatype.datatype_code
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setDatatype_code(String datatype_code) {
        this.datatype_code = datatype_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_datatype.datatype_name
     *
     * @return the value of ida_datatype.datatype_name
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getDatatype_name() {
        return datatype_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_datatype.datatype_name
     *
     * @param datatype_name the value for ida_datatype.datatype_name
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setDatatype_name(String datatype_name) {
        this.datatype_name = datatype_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_datatype.discription
     *
     * @return the value of ida_datatype.discription
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getDiscription() {
        return discription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_datatype.discription
     *
     * @param discription the value for ida_datatype.discription
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setDiscription(String discription) {
        this.discription = discription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_datatype.creator
     *
     * @return the value of ida_datatype.creator
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_datatype.creator
     *
     * @param creator the value for ida_datatype.creator
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_datatype.created_time
     *
     * @return the value of ida_datatype.created_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getCreated_time() {
        return created_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_datatype.created_time
     *
     * @param created_time the value for ida_datatype.created_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setCreated_time(String created_time) {
        this.created_time = created_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_datatype.updated_time
     *
     * @return the value of ida_datatype.updated_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getUpdated_time() {
        return updated_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_datatype.updated_time
     *
     * @param updated_time the value for ida_datatype.updated_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setUpdated_time(String updated_time) {
        this.updated_time = updated_time;
    }
}