package big.strong.disheng.user.model;

public class IdaDatasource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_datasource.datasource_id
     *
     * @mbggenerated Tue Jul 21 20:08:07 CST 2020
     */
    private String datasource_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_datasource.datasource_name
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String datasource_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_datasource.discription
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String discription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_datasource.datasource_type
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String datasource_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_datasource.db_username
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String db_username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_datasource.db_password
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String db_password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_datasource.db_ip
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String db_ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_datasource.db_port
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String db_port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_datasource.db_name
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String db_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_datasource.creator
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_datasource.account_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String account_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_datasource.created_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String created_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_datasource.updated_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String updated_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_datasource.datasource_info
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String datasource_info;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_datasource.datasource_id
     *
     * @return the value of ida_datasource.datasource_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getDatasource_id() {
        return datasource_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_datasource.datasource_id
     *
     * @param datasource_id the value for ida_datasource.datasource_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setDatasource_id(String datasource_id) {
        this.datasource_id = datasource_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_datasource.datasource_name
     *
     * @return the value of ida_datasource.datasource_name
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getDatasource_name() {
        return datasource_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_datasource.datasource_name
     *
     * @param datasource_name the value for ida_datasource.datasource_name
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setDatasource_name(String datasource_name) {
        this.datasource_name = datasource_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_datasource.discription
     *
     * @return the value of ida_datasource.discription
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getDiscription() {
        return discription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_datasource.discription
     *
     * @param discription the value for ida_datasource.discription
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setDiscription(String discription) {
        this.discription = discription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_datasource.datasource_type
     *
     * @return the value of ida_datasource.datasource_type
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getDatasource_type() {
        return datasource_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_datasource.datasource_type
     *
     * @param datasource_type the value for ida_datasource.datasource_type
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setDatasource_type(String datasource_type) {
        this.datasource_type = datasource_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_datasource.db_username
     *
     * @return the value of ida_datasource.db_username
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getDb_username() {
        return db_username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_datasource.db_username
     *
     * @param db_username the value for ida_datasource.db_username
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setDb_username(String db_username) {
        this.db_username = db_username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_datasource.db_password
     *
     * @return the value of ida_datasource.db_password
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getDb_password() {
        return db_password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_datasource.db_password
     *
     * @param db_password the value for ida_datasource.db_password
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setDb_password(String db_password) {
        this.db_password = db_password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_datasource.db_ip
     *
     * @return the value of ida_datasource.db_ip
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getDb_ip() {
        return db_ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_datasource.db_ip
     *
     * @param db_ip the value for ida_datasource.db_ip
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setDb_ip(String db_ip) {
        this.db_ip = db_ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_datasource.db_port
     *
     * @return the value of ida_datasource.db_port
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getDb_port() {
        return db_port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_datasource.db_port
     *
     * @param db_port the value for ida_datasource.db_port
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setDb_port(String db_port) {
        this.db_port = db_port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_datasource.db_name
     *
     * @return the value of ida_datasource.db_name
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getDb_name() {
        return db_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_datasource.db_name
     *
     * @param db_name the value for ida_datasource.db_name
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setDb_name(String db_name) {
        this.db_name = db_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_datasource.creator
     *
     * @return the value of ida_datasource.creator
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_datasource.creator
     *
     * @param creator the value for ida_datasource.creator
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_datasource.account_id
     *
     * @return the value of ida_datasource.account_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_datasource.account_id
     *
     * @param account_id the value for ida_datasource.account_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_datasource.created_time
     *
     * @return the value of ida_datasource.created_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getCreated_time() {
        return created_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_datasource.created_time
     *
     * @param created_time the value for ida_datasource.created_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setCreated_time(String created_time) {
        this.created_time = created_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_datasource.updated_time
     *
     * @return the value of ida_datasource.updated_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getUpdated_time() {
        return updated_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_datasource.updated_time
     *
     * @param updated_time the value for ida_datasource.updated_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setUpdated_time(String updated_time) {
        this.updated_time = updated_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_datasource.datasource_info
     *
     * @return the value of ida_datasource.datasource_info
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getDatasource_info() {
        return datasource_info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_datasource.datasource_info
     *
     * @param datasource_info the value for ida_datasource.datasource_info
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setDatasource_info(String datasource_info) {
        this.datasource_info = datasource_info;
    }
}