package big.strong.disheng.user.model;

public class IdaDatasetItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_dataset_item.item_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String item_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_dataset_item.dataset_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String dataset_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_dataset_item.data_type
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String data_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_dataset_item.account_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String account_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_dataset_item.creator
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_dataset_item.created_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String created_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_dataset_item.item_content
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String item_content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_dataset_item.item_id
     *
     * @return the value of ida_dataset_item.item_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getItem_id() {
        return item_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_dataset_item.item_id
     *
     * @param item_id the value for ida_dataset_item.item_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setItem_id(String item_id) {
        this.item_id = item_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_dataset_item.dataset_id
     *
     * @return the value of ida_dataset_item.dataset_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getDataset_id() {
        return dataset_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_dataset_item.dataset_id
     *
     * @param dataset_id the value for ida_dataset_item.dataset_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setDataset_id(String dataset_id) {
        this.dataset_id = dataset_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_dataset_item.data_type
     *
     * @return the value of ida_dataset_item.data_type
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getData_type() {
        return data_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_dataset_item.data_type
     *
     * @param data_type the value for ida_dataset_item.data_type
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setData_type(String data_type) {
        this.data_type = data_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_dataset_item.account_id
     *
     * @return the value of ida_dataset_item.account_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_dataset_item.account_id
     *
     * @param account_id the value for ida_dataset_item.account_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_dataset_item.creator
     *
     * @return the value of ida_dataset_item.creator
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_dataset_item.creator
     *
     * @param creator the value for ida_dataset_item.creator
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_dataset_item.created_time
     *
     * @return the value of ida_dataset_item.created_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getCreated_time() {
        return created_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_dataset_item.created_time
     *
     * @param created_time the value for ida_dataset_item.created_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setCreated_time(String created_time) {
        this.created_time = created_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_dataset_item.item_content
     *
     * @return the value of ida_dataset_item.item_content
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getItem_content() {
        return item_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_dataset_item.item_content
     *
     * @param item_content the value for ida_dataset_item.item_content
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setItem_content(String item_content) {
        this.item_content = item_content;
    }
}