package big.strong.disheng.user.model;

public class IdaDataset {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_dataset.dataset_id
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    private String dataset_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_dataset.dataset_name
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    private String dataset_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_dataset.description
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_dataset.data_type
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    private String data_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_dataset.datasource_type
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    private String datasource_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_dataset.datasource_id
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    private String datasource_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_dataset.storage_path
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    private String storage_path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_dataset.account_id
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    private String account_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_dataset.creator
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_dataset.created_time
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    private String created_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_dataset.updated_time
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    private String updated_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_dataset.dataset_id
     *
     * @return the value of ida_dataset.dataset_id
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    public String getDataset_id() {
        return dataset_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_dataset.dataset_id
     *
     * @param dataset_id the value for ida_dataset.dataset_id
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    public void setDataset_id(String dataset_id) {
        this.dataset_id = dataset_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_dataset.dataset_name
     *
     * @return the value of ida_dataset.dataset_name
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    public String getDataset_name() {
        return dataset_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_dataset.dataset_name
     *
     * @param dataset_name the value for ida_dataset.dataset_name
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    public void setDataset_name(String dataset_name) {
        this.dataset_name = dataset_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_dataset.description
     *
     * @return the value of ida_dataset.description
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_dataset.description
     *
     * @param description the value for ida_dataset.description
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_dataset.data_type
     *
     * @return the value of ida_dataset.data_type
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    public String getData_type() {
        return data_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_dataset.data_type
     *
     * @param data_type the value for ida_dataset.data_type
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    public void setData_type(String data_type) {
        this.data_type = data_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_dataset.datasource_type
     *
     * @return the value of ida_dataset.datasource_type
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    public String getDatasource_type() {
        return datasource_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_dataset.datasource_type
     *
     * @param datasource_type the value for ida_dataset.datasource_type
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    public void setDatasource_type(String datasource_type) {
        this.datasource_type = datasource_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_dataset.datasource_id
     *
     * @return the value of ida_dataset.datasource_id
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    public String getDatasource_id() {
        return datasource_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_dataset.datasource_id
     *
     * @param datasource_id the value for ida_dataset.datasource_id
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    public void setDatasource_id(String datasource_id) {
        this.datasource_id = datasource_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_dataset.storage_path
     *
     * @return the value of ida_dataset.storage_path
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    public String getStorage_path() {
        return storage_path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_dataset.storage_path
     *
     * @param storage_path the value for ida_dataset.storage_path
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    public void setStorage_path(String storage_path) {
        this.storage_path = storage_path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_dataset.account_id
     *
     * @return the value of ida_dataset.account_id
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_dataset.account_id
     *
     * @param account_id the value for ida_dataset.account_id
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_dataset.creator
     *
     * @return the value of ida_dataset.creator
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_dataset.creator
     *
     * @param creator the value for ida_dataset.creator
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_dataset.created_time
     *
     * @return the value of ida_dataset.created_time
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    public String getCreated_time() {
        return created_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_dataset.created_time
     *
     * @param created_time the value for ida_dataset.created_time
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    public void setCreated_time(String created_time) {
        this.created_time = created_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_dataset.updated_time
     *
     * @return the value of ida_dataset.updated_time
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    public String getUpdated_time() {
        return updated_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_dataset.updated_time
     *
     * @param updated_time the value for ida_dataset.updated_time
     *
     * @mbggenerated Wed Jul 22 11:40:42 CST 2020
     */
    public void setUpdated_time(String updated_time) {
        this.updated_time = updated_time;
    }
}