package big.strong.disheng.user.model;

public class IdaTaskType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_type.task_type_code
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String task_type_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_type.task_type_name
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String task_type_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_type.description
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_type.creator
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_type.created_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String created_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_type.updated_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String updated_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_type.task_type_code
     *
     * @return the value of ida_task_type.task_type_code
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getTask_type_code() {
        return task_type_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_type.task_type_code
     *
     * @param task_type_code the value for ida_task_type.task_type_code
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setTask_type_code(String task_type_code) {
        this.task_type_code = task_type_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_type.task_type_name
     *
     * @return the value of ida_task_type.task_type_name
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getTask_type_name() {
        return task_type_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_type.task_type_name
     *
     * @param task_type_name the value for ida_task_type.task_type_name
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setTask_type_name(String task_type_name) {
        this.task_type_name = task_type_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_type.description
     *
     * @return the value of ida_task_type.description
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_type.description
     *
     * @param description the value for ida_task_type.description
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_type.creator
     *
     * @return the value of ida_task_type.creator
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_type.creator
     *
     * @param creator the value for ida_task_type.creator
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_type.created_time
     *
     * @return the value of ida_task_type.created_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getCreated_time() {
        return created_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_type.created_time
     *
     * @param created_time the value for ida_task_type.created_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setCreated_time(String created_time) {
        this.created_time = created_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_type.updated_time
     *
     * @return the value of ida_task_type.updated_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getUpdated_time() {
        return updated_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_type.updated_time
     *
     * @param updated_time the value for ida_task_type.updated_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setUpdated_time(String updated_time) {
        this.updated_time = updated_time;
    }
}