package big.strong.disheng.user.model;

public class IdaTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task.task_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String task_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task.task_name
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String task_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task.description
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task.task_type
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String task_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task.task_state
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String task_state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task.dataset_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String dataset_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task.is_team
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String is_team;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task.team_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String team_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task.task_tag_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String task_tag_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task.task_dict_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String task_dict_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task.task_item_num
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private Integer task_item_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task.output_path
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String output_path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task.acceptance_rate
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private Float acceptance_rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task.account_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String account_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task.creator
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task.created_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String created_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task.updated_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String updated_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task.task_id
     *
     * @return the value of ida_task.task_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getTask_id() {
        return task_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task.task_id
     *
     * @param task_id the value for ida_task.task_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setTask_id(String task_id) {
        this.task_id = task_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task.task_name
     *
     * @return the value of ida_task.task_name
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getTask_name() {
        return task_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task.task_name
     *
     * @param task_name the value for ida_task.task_name
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setTask_name(String task_name) {
        this.task_name = task_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task.description
     *
     * @return the value of ida_task.description
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task.description
     *
     * @param description the value for ida_task.description
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task.task_type
     *
     * @return the value of ida_task.task_type
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getTask_type() {
        return task_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task.task_type
     *
     * @param task_type the value for ida_task.task_type
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setTask_type(String task_type) {
        this.task_type = task_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task.task_state
     *
     * @return the value of ida_task.task_state
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getTask_state() {
        return task_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task.task_state
     *
     * @param task_state the value for ida_task.task_state
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setTask_state(String task_state) {
        this.task_state = task_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task.dataset_id
     *
     * @return the value of ida_task.dataset_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getDataset_id() {
        return dataset_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task.dataset_id
     *
     * @param dataset_id the value for ida_task.dataset_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setDataset_id(String dataset_id) {
        this.dataset_id = dataset_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task.is_team
     *
     * @return the value of ida_task.is_team
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getIs_team() {
        return is_team;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task.is_team
     *
     * @param is_team the value for ida_task.is_team
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setIs_team(String is_team) {
        this.is_team = is_team;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task.team_id
     *
     * @return the value of ida_task.team_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getTeam_id() {
        return team_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task.team_id
     *
     * @param team_id the value for ida_task.team_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setTeam_id(String team_id) {
        this.team_id = team_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task.task_tag_id
     *
     * @return the value of ida_task.task_tag_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getTask_tag_id() {
        return task_tag_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task.task_tag_id
     *
     * @param task_tag_id the value for ida_task.task_tag_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setTask_tag_id(String task_tag_id) {
        this.task_tag_id = task_tag_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task.task_dict_id
     *
     * @return the value of ida_task.task_dict_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getTask_dict_id() {
        return task_dict_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task.task_dict_id
     *
     * @param task_dict_id the value for ida_task.task_dict_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setTask_dict_id(String task_dict_id) {
        this.task_dict_id = task_dict_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task.task_item_num
     *
     * @return the value of ida_task.task_item_num
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public Integer getTask_item_num() {
        return task_item_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task.task_item_num
     *
     * @param task_item_num the value for ida_task.task_item_num
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setTask_item_num(Integer task_item_num) {
        this.task_item_num = task_item_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task.output_path
     *
     * @return the value of ida_task.output_path
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getOutput_path() {
        return output_path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task.output_path
     *
     * @param output_path the value for ida_task.output_path
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setOutput_path(String output_path) {
        this.output_path = output_path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task.acceptance_rate
     *
     * @return the value of ida_task.acceptance_rate
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public Float getAcceptance_rate() {
        return acceptance_rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task.acceptance_rate
     *
     * @param acceptance_rate the value for ida_task.acceptance_rate
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setAcceptance_rate(Float acceptance_rate) {
        this.acceptance_rate = acceptance_rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task.account_id
     *
     * @return the value of ida_task.account_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task.account_id
     *
     * @param account_id the value for ida_task.account_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task.creator
     *
     * @return the value of ida_task.creator
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task.creator
     *
     * @param creator the value for ida_task.creator
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task.created_time
     *
     * @return the value of ida_task.created_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getCreated_time() {
        return created_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task.created_time
     *
     * @param created_time the value for ida_task.created_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setCreated_time(String created_time) {
        this.created_time = created_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task.updated_time
     *
     * @return the value of ida_task.updated_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getUpdated_time() {
        return updated_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task.updated_time
     *
     * @param updated_time the value for ida_task.updated_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setUpdated_time(String updated_time) {
        this.updated_time = updated_time;
    }
}