package big.strong.disheng.user.model;

public class IdaTagItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_tag_item.item_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String item_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_tag_item.item_name
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String item_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_tag_item.item_sign
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String item_sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_tag_item.item_color
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String item_color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_tag_item.tag_set_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String tag_set_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_tag_item.creator
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_tag_item.account_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String account_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_tag_item.created_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String created_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_tag_item.updated_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String updated_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_tag_item.item_id
     *
     * @return the value of ida_tag_item.item_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getItem_id() {
        return item_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_tag_item.item_id
     *
     * @param item_id the value for ida_tag_item.item_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setItem_id(String item_id) {
        this.item_id = item_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_tag_item.item_name
     *
     * @return the value of ida_tag_item.item_name
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getItem_name() {
        return item_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_tag_item.item_name
     *
     * @param item_name the value for ida_tag_item.item_name
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setItem_name(String item_name) {
        this.item_name = item_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_tag_item.item_sign
     *
     * @return the value of ida_tag_item.item_sign
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getItem_sign() {
        return item_sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_tag_item.item_sign
     *
     * @param item_sign the value for ida_tag_item.item_sign
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setItem_sign(String item_sign) {
        this.item_sign = item_sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_tag_item.item_color
     *
     * @return the value of ida_tag_item.item_color
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getItem_color() {
        return item_color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_tag_item.item_color
     *
     * @param item_color the value for ida_tag_item.item_color
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setItem_color(String item_color) {
        this.item_color = item_color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_tag_item.tag_set_id
     *
     * @return the value of ida_tag_item.tag_set_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getTag_set_id() {
        return tag_set_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_tag_item.tag_set_id
     *
     * @param tag_set_id the value for ida_tag_item.tag_set_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setTag_set_id(String tag_set_id) {
        this.tag_set_id = tag_set_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_tag_item.creator
     *
     * @return the value of ida_tag_item.creator
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_tag_item.creator
     *
     * @param creator the value for ida_tag_item.creator
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_tag_item.account_id
     *
     * @return the value of ida_tag_item.account_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_tag_item.account_id
     *
     * @param account_id the value for ida_tag_item.account_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_tag_item.created_time
     *
     * @return the value of ida_tag_item.created_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getCreated_time() {
        return created_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_tag_item.created_time
     *
     * @param created_time the value for ida_tag_item.created_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setCreated_time(String created_time) {
        this.created_time = created_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_tag_item.updated_time
     *
     * @return the value of ida_tag_item.updated_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getUpdated_time() {
        return updated_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_tag_item.updated_time
     *
     * @param updated_time the value for ida_tag_item.updated_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setUpdated_time(String updated_time) {
        this.updated_time = updated_time;
    }
}