package big.strong.disheng.user.model;

public class IdaTag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_tag.tag_set_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String tag_set_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_tag.tag_set_name
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String tag_set_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_tag.description
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_tag.tag_type
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String tag_type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_tag.tag_set_id
     *
     * @return the value of ida_tag.tag_set_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getTag_set_id() {
        return tag_set_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_tag.tag_set_id
     *
     * @param tag_set_id the value for ida_tag.tag_set_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setTag_set_id(String tag_set_id) {
        this.tag_set_id = tag_set_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_tag.tag_set_name
     *
     * @return the value of ida_tag.tag_set_name
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getTag_set_name() {
        return tag_set_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_tag.tag_set_name
     *
     * @param tag_set_name the value for ida_tag.tag_set_name
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setTag_set_name(String tag_set_name) {
        this.tag_set_name = tag_set_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_tag.description
     *
     * @return the value of ida_tag.description
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_tag.description
     *
     * @param description the value for ida_tag.description
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_tag.tag_type
     *
     * @return the value of ida_tag.tag_type
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getTag_type() {
        return tag_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_tag.tag_type
     *
     * @param tag_type the value for ida_tag.tag_type
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setTag_type(String tag_type) {
        this.tag_type = tag_type;
    }
}