package big.strong.disheng.user.model;

public class IdaTeamMember {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_team_member.member_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String member_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_team_member.user_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_team_member.user_name
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String user_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_team_member.member_role
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String member_role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_team_member.team_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String team_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_team_member.creator
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_team_member.account_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String account_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_team_member.created_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String created_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_team_member.updated_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String updated_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_team_member.member_id
     *
     * @return the value of ida_team_member.member_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getMember_id() {
        return member_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_team_member.member_id
     *
     * @param member_id the value for ida_team_member.member_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setMember_id(String member_id) {
        this.member_id = member_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_team_member.user_id
     *
     * @return the value of ida_team_member.user_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_team_member.user_id
     *
     * @param user_id the value for ida_team_member.user_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_team_member.user_name
     *
     * @return the value of ida_team_member.user_name
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getUser_name() {
        return user_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_team_member.user_name
     *
     * @param user_name the value for ida_team_member.user_name
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setUser_name(String user_name) {
        this.user_name = user_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_team_member.member_role
     *
     * @return the value of ida_team_member.member_role
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getMember_role() {
        return member_role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_team_member.member_role
     *
     * @param member_role the value for ida_team_member.member_role
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setMember_role(String member_role) {
        this.member_role = member_role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_team_member.team_id
     *
     * @return the value of ida_team_member.team_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getTeam_id() {
        return team_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_team_member.team_id
     *
     * @param team_id the value for ida_team_member.team_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setTeam_id(String team_id) {
        this.team_id = team_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_team_member.creator
     *
     * @return the value of ida_team_member.creator
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_team_member.creator
     *
     * @param creator the value for ida_team_member.creator
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_team_member.account_id
     *
     * @return the value of ida_team_member.account_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_team_member.account_id
     *
     * @param account_id the value for ida_team_member.account_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_team_member.created_time
     *
     * @return the value of ida_team_member.created_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getCreated_time() {
        return created_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_team_member.created_time
     *
     * @param created_time the value for ida_team_member.created_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setCreated_time(String created_time) {
        this.created_time = created_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_team_member.updated_time
     *
     * @return the value of ida_team_member.updated_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getUpdated_time() {
        return updated_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_team_member.updated_time
     *
     * @param updated_time the value for ida_team_member.updated_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setUpdated_time(String updated_time) {
        this.updated_time = updated_time;
    }
}