package big.strong.disheng.user.model;

public class IdaTaskCheckSample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_check_sample.sample_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String sample_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_check_sample.task_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String task_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_check_sample.sample_rate
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private Float sample_rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_check_sample.acceptence_rate
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private Float acceptence_rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_check_sample.account_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String account_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_check_sample.creator
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_check_sample.created_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String created_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_check_sample.updated_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String updated_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_check_sample.sample_id
     *
     * @return the value of ida_task_check_sample.sample_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getSample_id() {
        return sample_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_check_sample.sample_id
     *
     * @param sample_id the value for ida_task_check_sample.sample_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setSample_id(String sample_id) {
        this.sample_id = sample_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_check_sample.task_id
     *
     * @return the value of ida_task_check_sample.task_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getTask_id() {
        return task_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_check_sample.task_id
     *
     * @param task_id the value for ida_task_check_sample.task_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setTask_id(String task_id) {
        this.task_id = task_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_check_sample.sample_rate
     *
     * @return the value of ida_task_check_sample.sample_rate
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public Float getSample_rate() {
        return sample_rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_check_sample.sample_rate
     *
     * @param sample_rate the value for ida_task_check_sample.sample_rate
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setSample_rate(Float sample_rate) {
        this.sample_rate = sample_rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_check_sample.acceptence_rate
     *
     * @return the value of ida_task_check_sample.acceptence_rate
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public Float getAcceptence_rate() {
        return acceptence_rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_check_sample.acceptence_rate
     *
     * @param acceptence_rate the value for ida_task_check_sample.acceptence_rate
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setAcceptence_rate(Float acceptence_rate) {
        this.acceptence_rate = acceptence_rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_check_sample.account_id
     *
     * @return the value of ida_task_check_sample.account_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_check_sample.account_id
     *
     * @param account_id the value for ida_task_check_sample.account_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_check_sample.creator
     *
     * @return the value of ida_task_check_sample.creator
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_check_sample.creator
     *
     * @param creator the value for ida_task_check_sample.creator
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_check_sample.created_time
     *
     * @return the value of ida_task_check_sample.created_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getCreated_time() {
        return created_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_check_sample.created_time
     *
     * @param created_time the value for ida_task_check_sample.created_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setCreated_time(String created_time) {
        this.created_time = created_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_check_sample.updated_time
     *
     * @return the value of ida_task_check_sample.updated_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getUpdated_time() {
        return updated_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_check_sample.updated_time
     *
     * @param updated_time the value for ida_task_check_sample.updated_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setUpdated_time(String updated_time) {
        this.updated_time = updated_time;
    }
}