package big.strong.disheng.user.model;

public class IdaTaskItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_item.task_item_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String task_item_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_item.task_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String task_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_item.dataset_item_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String dataset_item_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_item.labeler
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String labeler;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_item.reviewer
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String reviewer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_item.checker
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String checker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_item.item_state
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String item_state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_item.account_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String account_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_item.creator
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_item.created_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String created_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_item.updated_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String updated_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_item.item_label_result
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String item_label_result;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_item.task_item_id
     *
     * @return the value of ida_task_item.task_item_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getTask_item_id() {
        return task_item_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_item.task_item_id
     *
     * @param task_item_id the value for ida_task_item.task_item_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setTask_item_id(String task_item_id) {
        this.task_item_id = task_item_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_item.task_id
     *
     * @return the value of ida_task_item.task_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getTask_id() {
        return task_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_item.task_id
     *
     * @param task_id the value for ida_task_item.task_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setTask_id(String task_id) {
        this.task_id = task_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_item.dataset_item_id
     *
     * @return the value of ida_task_item.dataset_item_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getDataset_item_id() {
        return dataset_item_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_item.dataset_item_id
     *
     * @param dataset_item_id the value for ida_task_item.dataset_item_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setDataset_item_id(String dataset_item_id) {
        this.dataset_item_id = dataset_item_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_item.labeler
     *
     * @return the value of ida_task_item.labeler
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getLabeler() {
        return labeler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_item.labeler
     *
     * @param labeler the value for ida_task_item.labeler
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setLabeler(String labeler) {
        this.labeler = labeler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_item.reviewer
     *
     * @return the value of ida_task_item.reviewer
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getReviewer() {
        return reviewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_item.reviewer
     *
     * @param reviewer the value for ida_task_item.reviewer
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setReviewer(String reviewer) {
        this.reviewer = reviewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_item.checker
     *
     * @return the value of ida_task_item.checker
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getChecker() {
        return checker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_item.checker
     *
     * @param checker the value for ida_task_item.checker
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setChecker(String checker) {
        this.checker = checker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_item.item_state
     *
     * @return the value of ida_task_item.item_state
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getItem_state() {
        return item_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_item.item_state
     *
     * @param item_state the value for ida_task_item.item_state
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setItem_state(String item_state) {
        this.item_state = item_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_item.account_id
     *
     * @return the value of ida_task_item.account_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_item.account_id
     *
     * @param account_id the value for ida_task_item.account_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_item.creator
     *
     * @return the value of ida_task_item.creator
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_item.creator
     *
     * @param creator the value for ida_task_item.creator
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_item.created_time
     *
     * @return the value of ida_task_item.created_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getCreated_time() {
        return created_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_item.created_time
     *
     * @param created_time the value for ida_task_item.created_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setCreated_time(String created_time) {
        this.created_time = created_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_item.updated_time
     *
     * @return the value of ida_task_item.updated_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getUpdated_time() {
        return updated_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_item.updated_time
     *
     * @param updated_time the value for ida_task_item.updated_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setUpdated_time(String updated_time) {
        this.updated_time = updated_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_item.item_label_result
     *
     * @return the value of ida_task_item.item_label_result
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getItem_label_result() {
        return item_label_result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_item.item_label_result
     *
     * @param item_label_result the value for ida_task_item.item_label_result
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setItem_label_result(String item_label_result) {
        this.item_label_result = item_label_result;
    }
}