package big.strong.disheng.user.model;

public class IdaTeam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_team.team_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String team_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_team.team_name
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String team_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_team.description
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_team.creator
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_team.account_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String account_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_team.created_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String created_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_team.updated_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    private String updated_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_team.team_id
     *
     * @return the value of ida_team.team_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getTeam_id() {
        return team_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_team.team_id
     *
     * @param team_id the value for ida_team.team_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setTeam_id(String team_id) {
        this.team_id = team_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_team.team_name
     *
     * @return the value of ida_team.team_name
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getTeam_name() {
        return team_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_team.team_name
     *
     * @param team_name the value for ida_team.team_name
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setTeam_name(String team_name) {
        this.team_name = team_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_team.description
     *
     * @return the value of ida_team.description
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_team.description
     *
     * @param description the value for ida_team.description
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_team.creator
     *
     * @return the value of ida_team.creator
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_team.creator
     *
     * @param creator the value for ida_team.creator
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_team.account_id
     *
     * @return the value of ida_team.account_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_team.account_id
     *
     * @param account_id the value for ida_team.account_id
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_team.created_time
     *
     * @return the value of ida_team.created_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getCreated_time() {
        return created_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_team.created_time
     *
     * @param created_time the value for ida_team.created_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setCreated_time(String created_time) {
        this.created_time = created_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_team.updated_time
     *
     * @return the value of ida_team.updated_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public String getUpdated_time() {
        return updated_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_team.updated_time
     *
     * @param updated_time the value for ida_team.updated_time
     *
     * @mbggenerated Tue Jul 21 20:08:08 CST 2020
     */
    public void setUpdated_time(String updated_time) {
        this.updated_time = updated_time;
    }
}