package big.strong.disheng.user.model;

public class IdaTaskItemHist {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_item_hist.hist_id
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    private String hist_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_item_hist.task_item_id
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    private String task_item_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_item_hist.datasetitem_id
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    private String datasetitem_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_item_hist.hist_handler
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    private String hist_handler;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_item_hist.hist_type
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    private String hist_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_item_hist.hist_feedback
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    private String hist_feedback;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_item_hist.ref_check_sample
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    private String ref_check_sample;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_item_hist.account_id
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    private String account_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_item_hist.creator
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_item_hist.created_time
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    private String created_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ida_task_item_hist.updated_time
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    private String updated_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_item_hist.hist_id
     *
     * @return the value of ida_task_item_hist.hist_id
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    public String getHist_id() {
        return hist_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_item_hist.hist_id
     *
     * @param hist_id the value for ida_task_item_hist.hist_id
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    public void setHist_id(String hist_id) {
        this.hist_id = hist_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_item_hist.task_item_id
     *
     * @return the value of ida_task_item_hist.task_item_id
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    public String getTask_item_id() {
        return task_item_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_item_hist.task_item_id
     *
     * @param task_item_id the value for ida_task_item_hist.task_item_id
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    public void setTask_item_id(String task_item_id) {
        this.task_item_id = task_item_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_item_hist.datasetitem_id
     *
     * @return the value of ida_task_item_hist.datasetitem_id
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    public String getDatasetitem_id() {
        return datasetitem_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_item_hist.datasetitem_id
     *
     * @param datasetitem_id the value for ida_task_item_hist.datasetitem_id
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    public void setDatasetitem_id(String datasetitem_id) {
        this.datasetitem_id = datasetitem_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_item_hist.hist_handler
     *
     * @return the value of ida_task_item_hist.hist_handler
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    public String getHist_handler() {
        return hist_handler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_item_hist.hist_handler
     *
     * @param hist_handler the value for ida_task_item_hist.hist_handler
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    public void setHist_handler(String hist_handler) {
        this.hist_handler = hist_handler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_item_hist.hist_type
     *
     * @return the value of ida_task_item_hist.hist_type
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    public String getHist_type() {
        return hist_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_item_hist.hist_type
     *
     * @param hist_type the value for ida_task_item_hist.hist_type
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    public void setHist_type(String hist_type) {
        this.hist_type = hist_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_item_hist.hist_feedback
     *
     * @return the value of ida_task_item_hist.hist_feedback
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    public String getHist_feedback() {
        return hist_feedback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_item_hist.hist_feedback
     *
     * @param hist_feedback the value for ida_task_item_hist.hist_feedback
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    public void setHist_feedback(String hist_feedback) {
        this.hist_feedback = hist_feedback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_item_hist.ref_check_sample
     *
     * @return the value of ida_task_item_hist.ref_check_sample
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    public String getRef_check_sample() {
        return ref_check_sample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_item_hist.ref_check_sample
     *
     * @param ref_check_sample the value for ida_task_item_hist.ref_check_sample
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    public void setRef_check_sample(String ref_check_sample) {
        this.ref_check_sample = ref_check_sample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_item_hist.account_id
     *
     * @return the value of ida_task_item_hist.account_id
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_item_hist.account_id
     *
     * @param account_id the value for ida_task_item_hist.account_id
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_item_hist.creator
     *
     * @return the value of ida_task_item_hist.creator
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_item_hist.creator
     *
     * @param creator the value for ida_task_item_hist.creator
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_item_hist.created_time
     *
     * @return the value of ida_task_item_hist.created_time
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    public String getCreated_time() {
        return created_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_item_hist.created_time
     *
     * @param created_time the value for ida_task_item_hist.created_time
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    public void setCreated_time(String created_time) {
        this.created_time = created_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ida_task_item_hist.updated_time
     *
     * @return the value of ida_task_item_hist.updated_time
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    public String getUpdated_time() {
        return updated_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ida_task_item_hist.updated_time
     *
     * @param updated_time the value for ida_task_item_hist.updated_time
     *
     * @mbggenerated Wed Jul 22 09:59:34 CST 2020
     */
    public void setUpdated_time(String updated_time) {
        this.updated_time = updated_time;
    }
}